services:
  # Backend API Service
  - type: web
    name: moview-backend
    env: python
    region: ohio
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Static Site Service
  - type: web
    name: moview-frontend
    env: static
    region: ohio
    plan: free
    buildCommand: cd frontend && npm ci && REACT_APP_API_URL=https://moview-backend.onrender.com npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html